DROP TABLE IF EXISTS disease CASCADE;
DROP TABLE IF EXISTS patient_disease CASCADE;
DROP TABLE IF EXISTS treatment CASCADE;
DROP TABLE IF EXISTS patient_treatment CASCADE;
DROP TABLE IF EXISTS allergy CASCADE;
DROP TABLE IF EXISTS patient_allergy CASCADE;
DROP TABLE IF EXISTS patient_comment CASCADE;